feat: migrate to flakes
tr8team/helm-wrapper-template pull request #16
Opened 2023-09-29 02:29 UTC by ocind

2023-09-29 02:37 UTC, kirinnee requested changes

2023-09-29 02:37 UTC, kirinnee commented on chart/Chart.tpl.yaml
> +version: { { .Env.VERSION } }
this is wrong change
```suggestion
version: {{ .Env.VERSION }}
```

2023-09-29 02:37 UTC, kirinnee commented on nix/pre-commit.nix
> +      excludes = [ ".*vendor.*" ".*scaffold/templates/.*" ".*chart/.*" "pnpm-lock.yaml" "Changelog.md" "CommitConventions.md" ".*schema.json" ".*gattai_custom_actions/.*" ];
can remove `pnpm-lock.yaml` `.*scaffold/templates/.*` etc

2023-09-29 02:39 UTC, ocind commented on nix/pre-commit.nix
> +      excludes = [ ".*vendor.*" ".*scaffold/templates/.*" ".*chart/.*" "pnpm-lock.yaml" "Changelog.md" "CommitConventions.md" ".*schema.json" ".*gattai_custom_actions/.*" ];
fixed

2023-09-29 02:40 UTC, ocind commented on chart/Chart.tpl.yaml
> +version: { { .Env.VERSION } }
fixed

2023-09-29 02:44 UTC, kirinnee approved these changes

2023-09-29 02:45 UTC, merged

2023-10-06 01:35 UTC, gotrade-devops commented
:tada: This PR is included in version 1.6.0 :tada:

The release is available on [GitHub release](https://github.com/tr8team/template.wrapper-helm/releases/tag/v1.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: